---
title: "Financial Analysis"
author: "Pinak Nayak"
date: "06/06/2021"
output: pdf_document
---

```{r Financial Analysis}
#Data----
revenue <- c(14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 
             10305.32, 14379.96, 10713.97, 15433.50)
expenses <- c(12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 
              5821.12, 6976.93, 16618.61, 10054.37, 3803.96)

# Question----
# Find the:

# 1) Profit for each month
# 2) Profit after tax for each month (30% tax rate)
# 3) Profit margin for each month - equals to profit after tax divided by revenue 
# 4) Good months - where the profit after tax was greater than the mean for the year
# 5) Bad months - where the profit after tax was less than the mean for the year
# 6) The best month - where the profit after tax was max for the year 
# 7) The worst month - where the profit after tax was min for the year

# Stipulations:

#1) All results need to be presented as vectors
#2) Results for dollar values need to be calculated with $0.01 precision, but need to be
#   presented in units of $1000 with no decimal points.
#3) Results for the profit margin ratio need to be presented in units of % with no decimal 
#   points. 


# Profit for each month----

profit <- round(revenue - expenses, digits=2)
print(as.integer(profit))

# Profit after tax for each month (30% tax rate)----

taxedprofit <- round(profit * 0.7,digits=2)
print(as.integer(taxedprofit))


# Profit margin for each month - equals to profit after tax divided by revenue----

profitmargin <- round((taxedprofit/revenue)*100,digits=2)
print(as.integer(profitmargin))

# Good months - where the profit after tax was greater than the mean for the year----

taxedprofitmean <- mean(taxedprofit)

goodmonths <- taxedprofit > taxedprofitmean
print(goodmonths)

# Bad months - where the profit after tax was less than the mean for the year----

badmonths <- taxedprofit < taxedprofitmean
print(badmonths)

# The best month - where the profit after tax was max for the year----

bestmonth <- which.max(taxedprofit)
print(bestmonth)

# The worst month - where the profit after tax was min for the year----

worstmonth <- which.min(taxedprofit)
print(worstmonth)

# Units of 1000 ----

revenue.1000 <- round(revenue/1000)
expenses.1000 <- round(expenses/1000)
profit.1000 <- round(profit/1000)
taxedprofit.1000 <- round(taxedprofit/1000)

#Outputs----
print(revenue.1000)
print(expenses.1000)
print(profit.1000)
print(taxedprofit.1000)

